---
- hosts: sundaycams

  vars:
    backup_dest: backups

  tasks:
    - name: get sunday config
      become: true
      fetch:
        src: "{{ item }}"
        dest: "{{ backup_dest }}"
      with_items:
        - /etc/wpa_supplicant/wpa_supplicant.conf
        - /etc/ddclient.conf
        - /etc/default/ddclient
        - /etc/modules-load.d/modules.conf
        - /etc/motion/motion.conf
        - /etc/systemd/system/sunday-portfwd-tunnel.service
        - /home/{{ user }}/.ssh/config
