---
- hosts: sundaycams
  gather_facts: yes
  tasks:
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/editor.yml
    - import_tasks: tasks/vimrc.yml
    - import_tasks: tasks/tmux.conf.yml
    - import_tasks: tasks/afpd.yml
    - import_tasks: tasks/authorized_keys.yml
    - import_tasks: tasks/gmail.yml

    - name: install more packages
      become: true
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=present
      with_items:
        - motion
        - ddclient
        - natpmp-utils
        - miniupnpc

    - name: enable camera
      become: yes
      lineinfile:
        path: /etc/modules-load.d/modules.conf
        line: bcm2835-v4l2 
        create: yes

    - name: motion conf
      become: yes
      template:
        dest: /etc/motion/motion.conf
        src: templates/motion.conf.j2
        owner: root
      notify: restart services

    - name: ddclient conf
      become: yes
      template:
        dest: /etc/ddclient.conf
        src: templates/ddclient.conf.j2
        owner: root
      notify: restart services

    - name: ssh config
      become: yes
      template:
        dest: /home/{{ user }}/.ssh/config
        src: templates/ssh-config.j2
        owner: root

    - name: copy sunday-motion service
      become: true
      copy:
        src: files/sunday-motion.service
        dest: /etc/systemd/system/sunday-motion.service
        owner: root

    - name: ssh keys
      copy:
        src: ~/.ssh/{{ item }}
        dest: /home/{{ user }}/.ssh/{{ item }}
        mode: "400"
      with_items:
        - "{{ tunnel_key_name }}"
        - "{{ tunnel_key_name }}.pub"

    - name: copy systemd services
      become: yes
      copy:
        owner: root
        dest: /etc/systemd/system/sunday-{{ item }}
        src: files/{{ item }}
      with_items:
        - portfwd-tunnel.service
        - portfwd-natpmp@.service
        - portfwd-natpmp@22.timer
        - portfwd-upnp@.service
        - portfwd-upnp@22.timer

          #- name: disable default motion service
          #  become: yes
          #  systemd:
          #    name: motion
          #    state: stopped
          #    enabled: false
          #    masked: true
          #    daemon_reload: true

    - name: enable services
      become: yes
      systemd:
        name: "{{ item }}"
        enabled: yes
        daemon_reload: true
      with_items:
        - ddclient
        - sunday-motion
        - sunday-portfwd-natpmp@22.timer
        - sunday-portfwd-upnp@22.timer
        - sunday-portfwd-tunnel.service

    - name: start services
      become: yes
      systemd:
        name: "{{ item }}"
        state: started
        daemon_reload: true
      with_items:
        - ddclient
        - sunday-motion
        - sunday-portfwd-natpmp@22.timer
        - sunday-portfwd-upnp@22.timer
        - sunday-portfwd-tunnel.service

  handlers:
    - name: restart services
      become: yes
      systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - ddclient
        - sunday-motion
        - sunday-portfwd-natpmp@22.timer
        - sunday-portfwd-upnp@22.timer
        - sunday-portfwd-tunnel.service

