- name: install apt packages
  become: true
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
    - avahi-daemon

- name: install afpd.service
  become: yes
  copy:
    src: files/afpd.service
    dest: /etc/avahi/services/afpd.service

