# https://wiki.debian.org/HowTo/ChangeHostname

- name: Set the hostname
  become: yes
  command: hostnamectl set-hostname "{{ hostname }}"

- name: root email alias
  become: true
  lineinfile:
    path: /etc/hosts
    state: present
    line: 127.0.0.1	{{ hostname }}
